name: CI

on:
  push:
    branches: 
      - main

jobs:
  build-core-and-ui:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 检出代码
    - uses: actions/checkout@v2

    # 构建ui
    - name: Build UI
      run:  |
        echo RELEASE.$(date "+%Y-%m-%d_%H-%M-%S") > docker.tag
        tag=$(cat docker.tag)
        sed "s@Digger Version v0.0.1@Digger Version $tag@g" -i ui/src/components/main/main.vue
        sh build-ui.sh

    # 构建镜像
    - name: Build and Push Docker Image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        tag=$(cat docker.tag)
        echo "tag is $tag"
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        sudo docker buildx create --use --name builder
        sudo docker buildx inspect builder --bootstrap
        sudo docker buildx build -t hehety/digger:${tag} -t hehety/digger:latest --platform=linux/arm,linux/arm64,linux/amd64 . --push --no-cache
